version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Change this if your Go app listens on a different port
    volumes:
      - ./data:/app/data